### ISSUE TITLE
Continue updating and other models support

### ISSUE THREAD

**Issue by LiRed7** [Wilson-ZheLin/Streamline-Analyst#3]
1.Will this project continue to be updated?
2.I transformed the project to support China Baidu's ERNIE Bot model, but there were some small problems。I was a python engineer transferred from Java, I could not solve these problems very well。Can I ask for your help？

**Comment by Wilson-ZheLin** [comment]
Hi Lihonghong,

Thank you very much for your interest in this project. I have a full-time job in New York at this time, so this project may not see major updates in the short term. However, if there is anything I can help with, please feel free to let me know, I would love to get in touch with a wider variety of models :)

**Comment by LiRed7** [comment]
> Hi Lihonghong,
> 
> Thank you very much for your interest in this project. I have a full-time job in New York at this time, so this project may not see major updates in the short term. However, if there is anything I can help with, please feel free to let me know, I would love to get in touch with a wider variety of models :)

Hello: Wilson ZheLin
I am a developer from China who self-taught Python programming. I saw this project on GitHub and I am very interested in it. Therefore, I have made modifications to this project and integrated other large models, all of which are self-developed LLMs in China. For example, Wenyin Yiyan from Baidu in China and Spark3.5 Max from iFlytek in China. However, since I have only been self-taught in Python for over a month, I am still unable to do so. Thank you for your help.

1. As shown in the figure below, I have adjusted all other parameters that are not distinguished and calculated normally. However, the column3 data parameter here is always incorrect, but I don't know how to modify it?

![col3](https://github.com/Wilson-ZheLin/Streamline-Analyst/assets/62365438/e258c10f-e31a-49e0-b643-fc0765cbab55)
![error_col3](https://github.com/Wilson-ZheLin/Streamline-Analyst/assets/62365438/e5a04017-9e71-4386-bda2-70ac939c8c38)
data for test:
![test_data](https://github.com/Wilson-ZheLin/Streamline-Analyst/assets/62365438/0e6e14d7-bae9-4c15-a0c6-f1b063f2099c)


2.Because I am not an expert in the field of mathematics, the data required for my project is not very sensitive and I always cannot find the correct output parameter data. I would like to obtain a correct parameter from you for my reference**

**Comment by Wilson-ZheLin** [comment]
Hi 👋，

1. 从你发的报错截图来看，问题是出在训练XGBoost模型这一步骤，具体成因应该是输入的数据不太符合预期。如果代码已经执行到了column3这一步，那么你对之前步骤中的、大模型相关的调整应该已经生效了，但是依然建议检查大模型每一次的回复确认他们符合预期。

2. 从你的数据截图来看，你使用的数据和这个项目预期的数据形式可能有一点出入。这个项目的主要针对的场景是**机器学习(ML)模型**的一个自动化的实现，具体来说，目前版本的支持的任务是`分类预测模型`、`回归模型`，和`聚类模型`三种。我提供一些比较经典的数据集供测试参考：
 - **肺癌预测：**[survey lung cancer.csv](https://github.com/user-attachments/files/16054357/survey.lung.cancer.csv)
 - **鸢尾花分类**：[Iris.csv](https://github.com/user-attachments/files/16054410/Iris.csv)
 - **波士顿房价：**[HousingData.csv](https://github.com/user-attachments/files/16054380/HousingData.csv)

我的邮箱：[wilson.linzhe@gmail.com](wilson.linzhe@gmail.com) ，如果你对这个或者其他LLM项目需要帮助可以通过📧发送比较完整的代码，会比较方便定位问题。

**Comment by LiRed7** [comment]
Thank you very much for your support. 
After your guidance, I checked the return of the model and found that the data returned was incorrect for col3. After modification, it has been restored to normal. The data you provided has given me great inspiration. Thank you.
